version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: prostgress_meeting_room_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - data:/var/lib/postgresql/data
volumes:
  data:
    driver: local